# Generated by Django 5.0.6 on 2024-06-26 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_follow_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='users/images/anonymous.png', upload_to='users/%Y/%m/%d'),
        ),
    ]
